openapi: 3.1.0
info:
  title: API de candidatos alterdata
  summary: database de candidatos
  description: |
    Retorna users e informações sobre users no database de TinyTale.
    Retorna token de autorização para efetuar login em TinyTale
    Persiste os users cadastrados por TinyTale.
  termsOfService: https://tinytale.com/terms/
  contact:
    name: API Support
    url: https://www.tinytale.com/support
    email: support@tinytale.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1

externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io/'

servers:
- url: http://localhost:8080/
  description: The local development API server