openapi: 3.1.0
info:
  title: API de candidatos Alterdata
  summary: database de candidatos
  description: |
    Retorna informações sobre Candidatos promissores para Alterdata.
    As informações incluem:
    - Nome
    - Foto
    - Formação (SERRATEC, Tech4Me)
    - Currículo em PDF
    - Link para o perfil no LinkedIn
    - Lista de Anotações contendo comentários sobre o Candidato, o autor, e a data da anotação.
    - Soft Skills, Hard Skills e Deep Skills
  termsOfService: https://candidatos.com/terms/
  contact:
    name: API Support
    url: https://www.candidato.com/support
    email: support@candidato.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1

externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io/'

servers:
- url: http://localhost:8080/
  description: The local development API server
  
components:
  schemas:
    CandidatoDTO:
      type: object
      properties:
        id:
          type: long
          description: a id do candidato no db
        nome:
          type: string
          description: o nome do candidato
        email:
          type: string
          description: o email do candidato
        anotacoes:
          type: array
          items:
            $ref: '#/components/schemas/AnotacaoDTO'   		 
        softSkills:
            type: string
            description: soft skills do candidato
        deepSkills:
            type: string
            description: deep skills do candidato
        hardSkills:
            type: string
            description: hard skills do candidato
    CadastroDTO:
        type: object
        properties:	
          nome: 
           type: string
           description: nome do candidato
          email:
           type: string
           description: email do candidato
          linkedIn:
            type: string
            description: linkedin do candidato
          fotos:
            type: array
            items:
              type: string
              format: url
            description: lista de URLs das fotos do candidato
          anotacoes:
            type: array
            items:
              $ref: '#/components/schemas/AnotacaoDTO'   
    AnotacaoDTO:
         type: object
         properties:
           comentario: 
              type: string
              description: O comentario da pessoa que recomendou
           autor:
              type: string
              description: O nome do funcionário que recomendou o candidato
           dataDeCriacao:
              type: string
              format: date-time
              description: A data que a recomendação foi criada

paths:
  /candidatos:
    get:
      summary: Consulta todos os candidatos com paginação
      tags:
        - Pegar CANDIDATOS
      parameters:
        - name: page
          in: query
          description: Page number
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          description: Page size
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Retornou a lista de CANDIDATOS com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: '#/components/schemas/CandidatoDTO'
                  totalElements:
                    type: integer
                    example: 100
                  totalPages:
                    type: integer
                    example: 10
                  size:
                    type: integer
                    example: 10
                  number:
                    type: integer
                    example: 1
                  numberOfElements:
                    type: integer
                    example: 10
                  first:
                    type: boolean
                    example: false
    post:
      summary: Cadastra um candidato no database.
      operationId: cadastrarCandidato
      tags:
        - Cadastrar CANDIDATO
      description: Cadastra um candidato no database, se ele for único.
      requestBody:
        description: CadastroDTO
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CadastroDTO'
  