openapi: 3.1.0
info:
  title: API de candidatos Alterdata
  summary: database de candidatos
  description: |
    Retorna os Candidatos promissores para Alterdata
    Autoriza os usuários do RH
  termsOfService: https://candidatos.com/terms/
  contact:
    name: API Support
    url: https://www.candidato.com/support
    email: support@candidato.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1

externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io/'

servers:
- url: http://localhost:8080/
  description: The local development API server
  
components:
  schemas:
    CandidatoDTO:
      type: object
      properties:
        id:
          type: long
          description: a id do candidato no db
        nome:
          type: string
          description: o nome do candidato
        email:
          type: string
          description: o email do candidato
        recomedacoes:
          type: array
          itens:
            $ref: '#/components/schemas/ecomendacaoDTO'   		 
        softSkills:
            type: string
            description: soft skills do candidato
        deepSkills:
            type: string
            description: deep skills do candidato
        hardSkills:
            type: string
            description: hard skills do candidato
    CadastroDTO:
        type: object
        properties:	
          nome: 
           type: string
           description: nome do candidato
          email:
           type: string
           description: email do candidato
          linkedInLink:
            type: string
            description: linkedin do candidato
    RecomendacaoDTO:
         type: object
         properties:
           comentario: 
              type: string
              description: O comentario da pessoa que recomendou
           autor:
              type: string
              description: O nome do funcionário que recomendou o candidato
           dataDeCriacao:
              type: string
              format: date-time
              description: A data que a recomendação foi criada
paths:
  /candidatos:
    get:
      summary: Consulta todos os candidatos com paginação
      tags:
        - Pegar CANDIDATOS
      parameters:
        - name: page
          in: query
          description: Page number
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          description: Page size
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Retornou a lista de CANDIDATOS com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: '#/components/schemas/CandidatoDTO'
                  totalElements:
                    type: integer
                    example: 100
                  totalPages:
                    type: integer
                    example: 10
                  size:
                    type: integer
                    example: 10
                  number:
                    type: integer
                    example: 1
                  numberOfElements:
                    type: integer
                    example: 10
                  first:
                    type: boolean
                    example: false
    post:
      summary: Cadastra um candidato no database.
      operationId: cadastrarCandidato
      tags:
        - Cadastrar CANDIDATO
      description: |
        Cadastra o CANDIDATO se o email for único no database,
        Atribui o perfil do candidato a partir do código de perfil inserido
        Criptografa a senha inserida.
        Registra o momento de criação.
      requestBody:
        description: CadastroDTO contendo o email a ser validado, a senha a ser criptografada e o código do perfil do candidato
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CadastroDTO'
  